@startuml

!theme plain
title Mini Blog Finite State Machine

[*] --> HomePage : the user lands on the home page

state "Home Page" as HomePage {
  [*] --> GetPosts : Fetch posts
  [*] --> GetSession : Check user authentication
}

state "GetPosts" as GetPosts
state "GetSession" as GetSession

state "Account" as Account {
    [*] --> fetchProfileUser : fetch the user profile automatically
    [*] --> selectorAccount : the user clicks on the Setting/liked/saved icon
    state "liked post" as LikedPost
    state "saved post" as SavedPost
    state "settings" as Settings
}

state "Add Post" as AddPost {
    [*] -> fetchCategories : fetch the categories automatically
}

state "Auth" as Auth


state selectorAccount <<choice>>
selectorAccount: the user clicks on the account/liked/saved icon
selectorAccount --> Settings :  Setting icon
selectorAccount --> LikedPost : liked posts icon
selectorAccount --> SavedPost : saved posts icon

state "redirect auth" as redirectAuth <<sdlreceive>>
redirectAuth: the user is redirected to the auth page if not authenticated
redirectAuth --> Auth : the user is not authenticated
redirectAuth --> selectorAccount : the user is authenticated
redirectAuth --> AddPost : the user is authenticated and clicked on the add post icon
redirectAuth --> HomePage : the user is authenticated and clicked on the authentication icon

HomePage --> redirectAuth : the user clicks on the account/liked/bookmark icon, add post icon, or authentication icon
AddPost --> HomePage : the user clicks on the logo icon
Account --> HomePage : the user clicks on the logo icon
@enduml
