name: Docker Image CI

on:
  push:
    branches: [ master ]

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_ISA_BLOG_TOKEN: ${{ secrets.VERCEL_ISA_BLOG_TOKEN }}
  VERCEL_APP_NAME: ${{ secrets.VERCEL_APP_NAME }}
  VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
  VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}


jobs:
  build:
    name: Build and push Docker image to DockerHub
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: docker

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/node/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/isa-blog:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
