name: Deploy Preview -> vercel
on:
  push:
    branches:
      - develop

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_ISA_BLOG_TOKEN: ${{ secrets.VERCEL_ISA_BLOG_TOKEN }}
  VERCEL_APP_NAME: ${{ secrets.VERCEL_APP_NAME }}
  VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
  VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Compose
        run: |
          cp .env.dist .env 
          echo VERCEL_ISA_BLOG_TOKEN=${{ secrets.VERCEL_ISA_BLOG_TOKEN }} >> .env
          echo VERCEL_ORG_ID=${{ secrets.VERCEL_ORG_ID }} >> .env
          echo VERCEL_PROJECT_ID=${{ secrets.VERCEL_PROJECT_ID }} >> .env
          echo VERCEL_APP_NAME=${{ secrets.VERCEL_APP_NAME }} >> .env
          echo VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }} >> .env
          echo VITE_SUPABASE_ANON_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY }} >> .env
          docker compose build && docker compose up -d

      - name: setup environment
        run: |
          docker compose exec node /bin/bash setup.sh

      - name: setup vercel
        run: |
          docker compose exec node /bin/bash setup_vercel.sh

      - name: Build project
        run: docker compose exec node npm run vercel-build

      - name: Link vercel to project
        run: docker compose exec node vercel -n ${{ secrets.VERCEL_APP_NAME }} --yes  --token=${{ secrets.VERCEL_ISA_BLOG_TOKEN }}

      - name: Dump docker logs on failure using different shell
        if: failure()
        uses: jwalton/gh-docker-logs@v2
        with:
          shell: '/bin/sh'
